// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIfs2pvwwiXK_9-8YViW0eoJBWFLuLV44',
    appId: '1:825779638613:web:d6d6798f8621aa27655fdc',
    messagingSenderId: '825779638613',
    projectId: 'topsoldier',
    authDomain: 'topsoldier.firebaseapp.com',
    databaseURL:
        'https://topsoldier-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'topsoldier.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBePDmxN_LpZTHBmLuRMOFDnhTEDIYvh8',
    appId: '1:825779638613:android:622287ce32fb3717655fdc',
    messagingSenderId: '825779638613',
    projectId: 'topsoldier',
    databaseURL:
        'https://topsoldier-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'topsoldier.firebasestorage.app',
  );
}
